import type { FoodItem } from "@/lib/types";
import {
  Apple,
  CookingPot,
  Pizza,
  Sandwich,
  Vegan,
  Wheat,
  Citrus,
  Salad,
  Drumstick,
  GlassWater,
  Coffee,
  Egg,
  Croissant,
} from "lucide-react";

export const foodItems: FoodItem[] = [
  {
    id: "apple",
    name: "Apple",
    icon: Apple,
    quantities: ["1 medium (182g)", "1 small (154g)", "1 large (223g)"],
    imageId: "apple",
  },
  {
    id: "banana",
    name: "Banana",
    icon: Vegan,
    quantities: ["1 medium (118g)", "1 small (101g)", "1 large (136g)"],
    imageId: "banana",
  },
  {
    id: "orange",
    name: "Orange",
    icon: Citrus,
    quantities: ["1 medium (131g)", "1 small (96g)", "1 large (184g)"],
    imageId: "orange",
  },
  {
    id: "pizza",
    name: "Pizza",
    icon: Pizza,
    quantities: ["1 slice", "1 medium pizza", "100g"],
    imageId: "pizza",
  },
  {
    id: "burger",
    name: "Burger",
    icon: Sandwich,
    quantities: ["1 burger", "1 patty", "100g"],
    imageId: "burger",
  },
  {
    id: "salad",
    name: "Salad",
    icon: Salad,
    quantities: ["1 bowl", "1 plate", "100g"],
    imageId: "salad",
  },
  {
    id: "chicken-curry",
    name: "Chicken Curry",
    icon: Drumstick,
    quantities: ["1 bowl", "1 plate", "100g"],
    imageId: "chicken-curry",
  },
  {
    id: "rice",
    name: "Rice",
    icon: CookingPot,
    quantities: ["1 cup (cooked)", "1 plate", "100g"],
    imageId: "rice",
  },
  {
    id: "chapati",
    name: "Chapati",
    icon: Wheat,
    quantities: ["1 piece", "2 pieces", "100g"],
    imageId: "chapati",
  },
  {
    id: "dosa",
    name: "Dosa",
    icon: Vegan,
    quantities: ["1 piece", "2 pieces", "100g"],
    imageId: "dosa",
  },
  {
    id: "dal",
    name: "Dal (Lentils)",
    icon: CookingPot,
    quantities: ["1 bowl", "1 cup", "100g"],
    imageId: "dal",
  },
  {
    id: "milk",
    name: "Milk",
    icon: GlassWater,
    quantities: ["1 glass (250ml)", "1 cup", "100ml"],
    imageId: "milk",
  },
  {
    id: "coffee",
    name: "Coffee",
    icon: Coffee,
    quantities: ["1 cup (black)", "1 cup (with milk)", "1 espresso"],
    imageId: "coffee",
  },
  {
    id: "egg",
    name: "Egg",
    icon: Egg,
    quantities: ["1 large (boiled)", "1 large (fried)", "1 omelette"],
    imageId: "egg",
  },
  {
    id: "croissant",
    name: "Croissant",
    icon: Croissant,
    quantities: ["1 piece", "1 large piece", "100g"],
    imageId: "croissant",
  },
];
